# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'NEOnlinePKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NEOnlinePKDemo

  pod 'YXLogin'
  pod 'YYModel'
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'ReactiveObjC', '~> 3.1.0'
  pod 'M80AttributedLabel', '~> 1.3.1'
  pod 'Nama-lite', '7.3.2'
  pod 'SDWebImage', '5.11.1'
  
  # # Pods for app
  pod 'NELiveKit', '1.0.0'
  pod 'YXAlog_iOS'

  pod 'NIMSDK_LITE', '~> 8.11.0'
  pod 'NERtcSDK', '4.2.124'
  pod 'NEScreenShareHost', '0.1.0'
end
